### Valid request
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Nick",
  "lastName": "Miller",
  "age": 32
}


### Invalid request
POST http://localhost:8080/api/users
Content-Type: application/json

{
"name": "",
"lastName": "",
"age": 0
}

### Invalid request with method arg validation
POST http://localhost:8080/api/users/with-validation
Content-Type: application/json

{
  "name": null,
  "lastName": "",
  "age": 0
}

### Poor handling request
GET http://localhost:8080/api/users/poor-handling